# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background:rgb(246, 247, 233)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.predictSentence = QtWidgets.QTextEdit(self.centralwidget)
        self.predictSentence.setEnabled(True)
        self.predictSentence.setGeometry(QtCore.QRect(100, 190, 611, 141))
        self.predictSentence.setStyleSheet("background:white;\n"
"border-radius: 15px;")
        self.predictSentence.setObjectName("predictSentence")
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictButton.setGeometry(QtCore.QRect(580, 350, 131, 31))
        self.predictButton.setStyleSheet("QPushButton {\n"
"  background-color: #2b4d70;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 12px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  flex: 0 0 auto;\n"
"  font-family: \"Inter var\",ui-sans-serif,system-ui,-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.125rem;\n"
"  font-weight: 600;\n"
"  line-height: 1.5rem;\n"
"  padding: .75rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none #6B7280 solid;\n"
"  text-decoration-thickness: auto;\n"
"  transition-duration: .2s;\n"
"  transition-property: background-color,border-color,color,fill,stroke;\n"
"  transition-timing-function: cubic-bezier(.4, 0, 0.2, 1);\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: auto;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: #374151;\n"
"    opacity : 0.75;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 3px solid black;\n"
"}")
        self.predictButton.setObjectName("predictButton")
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel.setGeometry(QtCore.QRect(100, 160, 241, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.inputLabel.setFont(font)
        self.inputLabel.setStyleSheet("color : #2b4d70;")
        self.inputLabel.setObjectName("inputLabel")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(100, 410, 241, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.outputLabel.setFont(font)
        self.outputLabel.setStyleSheet("color : #2b4d70;")
        self.outputLabel.setObjectName("outputLabel")
        self.judul = QtWidgets.QLabel(self.centralwidget)
        self.judul.setGeometry(QtCore.QRect(90, 70, 751, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono Medium")
        font.setPointSize(12)
        self.judul.setFont(font)
        self.judul.setStyleSheet("color : #2b4d70;")
        self.judul.setObjectName("judul")
        self.outputText = QtWidgets.QTextEdit(self.centralwidget)
        self.outputText.setEnabled(True)
        self.outputText.setGeometry(QtCore.QRect(100, 440, 611, 81))
        self.outputText.setStyleSheet("background:white;\n"
"border-radius: 15px;")
        self.outputText.setReadOnly(True)
        self.outputText.setObjectName("outputText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie Mood"))
        self.predictButton.setText(_translate("MainWindow", "Predict"))
        self.inputLabel.setText(_translate("MainWindow", "Input Word to Predict :"))
        self.outputLabel.setText(_translate("MainWindow", "Output :"))
        self.judul.setText(_translate("MainWindow", "ANALISIS SENTIMEN PADA REVIEW ROTTEN TOMATOES MENGGUNAKAN LSTM"))

    def clearOutputText(self):
        self.outputText.clear()
        self.outputText.setPlainText('')

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
